// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/guestcourses": {
    params: {};
  };
  "/tutors": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/courses": {
    params: {};
  };
  "/dashboard/courses/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/dashboard/courses/:courseId/section/:sectionId/sub-section/:subSectionId": {
    params: {
      "courseId": string;
      "sectionId": string;
      "subSectionId": string;
    };
  };
  "/dashboard/add-course": {
    params: {};
  };
  "/dashboard/edit-course/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/dashboard/profile": {
    params: {};
  };
  "/dashboard/update-password": {
    params: {};
  };
  "/dashboard/delete-account": {
    params: {};
  };
  "/dashboard/wallet": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/catalog" | "/guestcourses" | "/tutors" | "/contact" | "/login" | "/register" | "/dashboard" | "/dashboard/courses" | "/dashboard/courses/:courseId" | "/dashboard/courses/:courseId/section/:sectionId/sub-section/:subSectionId" | "/dashboard/add-course" | "/dashboard/edit-course/:courseId" | "/dashboard/profile" | "/dashboard/update-password" | "/dashboard/delete-account" | "/dashboard/wallet" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "../pages/About.jsx": {
    id: "../pages/About";
    page: "/about";
  };
  "../pages/Catalog.jsx": {
    id: "../pages/Catalog";
    page: "/catalog";
  };
  "../pages/GuestCourses.jsx": {
    id: "../pages/GuestCourses";
    page: "/guestcourses";
  };
  "../pages/Tutors.jsx": {
    id: "../pages/Tutors";
    page: "/tutors";
  };
  "../pages/Contact.jsx": {
    id: "../pages/Contact";
    page: "/contact";
  };
  "../components/auth/login/Login.jsx": {
    id: "../components/auth/login/Login";
    page: "/login";
  };
  "../components/auth/register/Register.jsx": {
    id: "../components/auth/register/Register";
    page: "/register";
  };
  "DashboardLayout.tsx": {
    id: "DashboardLayout";
    page: "/dashboard" | "/dashboard/courses" | "/dashboard/courses/:courseId" | "/dashboard/courses/:courseId/section/:sectionId/sub-section/:subSectionId" | "/dashboard/add-course" | "/dashboard/edit-course/:courseId" | "/dashboard/profile" | "/dashboard/update-password" | "/dashboard/delete-account" | "/dashboard/wallet";
  };
  "routes/DashboardHome.tsx": {
    id: "routes/DashboardHome";
    page: "/dashboard";
  };
  "../pages/dashboard/Courses.jsx": {
    id: "../pages/dashboard/Courses";
    page: "/dashboard/courses";
  };
  "../pages/dashboard/ViewCourse.jsx": {
    id: "../pages/dashboard/ViewCourse";
    page: "/dashboard/courses/:courseId" | "/dashboard/courses/:courseId/section/:sectionId/sub-section/:subSectionId";
  };
  "../pages/dashboard/LectureViewer.jsx": {
    id: "../pages/dashboard/LectureViewer";
    page: "/dashboard/courses/:courseId/section/:sectionId/sub-section/:subSectionId";
  };
  "../pages/dashboard/AddCourses.jsx": {
    id: "../pages/dashboard/AddCourses";
    page: "/dashboard/add-course";
  };
  "../pages/dashboard/EditCourse.jsx": {
    id: "../pages/dashboard/EditCourse";
    page: "/dashboard/edit-course/:courseId";
  };
  "../pages/dashboard/Profile.jsx": {
    id: "../pages/dashboard/Profile";
    page: "/dashboard/profile";
  };
  "../pages/dashboard/UpdatePassword.jsx": {
    id: "../pages/dashboard/UpdatePassword";
    page: "/dashboard/update-password";
  };
  "../pages/dashboard/DeleteAccount.jsx": {
    id: "../pages/dashboard/DeleteAccount";
    page: "/dashboard/delete-account";
  };
  "../pages/dashboard/Wallet.jsx": {
    id: "../pages/dashboard/Wallet";
    page: "/dashboard/wallet";
  };
  "../components/auth/error/Error.tsx": {
    id: "../components/auth/error/Error";
    page: "/*";
  };
};